# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-31 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=250)),
                ('number_of_people', models.IntegerField()),
                ('capacity', models.IntegerField()),
            ],
        ),
    ]
