# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-31 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='image',
            field=models.CharField(default='https://www.arup.com/-/media/images/projects/b/bskyb/headersky-health-and-fitness-centre--bskyb-phase-2-osterley-hounslow-london-c-paul-carstairsarup4.jpg', max_length=250),
            preserve_default=False,
        ),
    ]
